//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Pimail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Pimail.Resources.EmailResource", typeof(EmailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the HTML body text.
        /// </summary>
        internal static string BodyHtml_Required_Error {
            get {
                return ResourceManager.GetString("BodyHtml_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the plain body text.
        /// </summary>
        internal static string BodyPlain_Required_Error {
            get {
                return ResourceManager.GetString("BodyPlain_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the from content encoding.
        /// </summary>
        internal static string ContentEncoding_Required_Error {
            get {
                return ResourceManager.GetString("ContentEncoding_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the from address.
        /// </summary>
        internal static string From_Required_Error {
            get {
                return ResourceManager.GetString("From_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the from header encoding.
        /// </summary>
        internal static string HeaderEncoding_Required_Error {
            get {
                return ResourceManager.GetString("HeaderEncoding_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size 128.
        /// </summary>
        internal static string Id_MaxLength_Error {
            get {
                return ResourceManager.GetString("Id_MaxLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size 3.
        /// </summary>
        internal static string Id_MinLength_Error {
            get {
                return ResourceManager.GetString("Id_MinLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the Id.
        /// </summary>
        internal static string Id_Required_Error {
            get {
                return ResourceManager.GetString("Id_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set if the body is HTML.
        /// </summary>
        internal static string IsBodyHtml_Required_Error {
            get {
                return ResourceManager.GetString("IsBodyHtml_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size 128.
        /// </summary>
        internal static string Name_MaxLength_Error {
            get {
                return ResourceManager.GetString("Name_MaxLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size 3.
        /// </summary>
        internal static string Name_MinLength_Error {
            get {
                return ResourceManager.GetString("Name_MinLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a name.
        /// </summary>
        internal static string Name_Required_Error {
            get {
                return ResourceManager.GetString("Name_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the from priority.
        /// </summary>
        internal static string Priority_Required_Error {
            get {
                return ResourceManager.GetString("Priority_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size 128.
        /// </summary>
        internal static string Subject_MaxLength_Error {
            get {
                return ResourceManager.GetString("Subject_MaxLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size 3.
        /// </summary>
        internal static string Subject_MinLength_Error {
            get {
                return ResourceManager.GetString("Subject_MinLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the subject.
        /// </summary>
        internal static string Subject_Required_Error {
            get {
                return ResourceManager.GetString("Subject_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size 3.
        /// </summary>
        internal static string To_MinLength_Error {
            get {
                return ResourceManager.GetString("To_MinLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the to address.
        /// </summary>
        internal static string To_Required_Error {
            get {
                return ResourceManager.GetString("To_Required_Error", resourceCulture);
            }
        }
    }
}
